### ISSUE TITLE
Disable in Private Browsing Mode

### ISSUE THREAD

**Issue by wresuolc** [internetarchive/FirefoxNoMore404s#3]
Another old comment:

The add-on should disable itself in private browsing mode to avoid potentially leaking [assumed] private data.

**Comment by rchrd2** [comment]
@wresuolc Do you happen to have any example code for this. I am having difficulty finding an example or documentation.

**Comment by bwinton** [comment]
Hey Richard!

Wil pointed me at this bug, and I don't have any example code, but you should be able to check `chrome.extension.inIncognitoContext` in client.js (as per [this document](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/extension/inIncognitoContext)).  Having said that, I think that might be a little too late, since it looks like you will already have made the request at that point.  So the other option is to copy [this code](http://stackoverflow.com/questions/14564540/google-chrome-how-to-determine-which-window-has-generated-webrequest#answer-14566243), which will give you a tab, and then you can check `tab.incognito` as described [here](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/Tab).

Sound good?  Please mention me if you run into any problems getting it to work, and I'll dig a little deeper to see what's going on…  🙂

**Comment by rchrd2** [comment]
Hi @bwinton, 
Thanks for the tips. I managed to get it working using your `tab.incognito` suggestion.

**Comment by bwinton** [comment]
(In general, if you run into any other problems with this WebExtension, please feel free to reach out to me.  It's been a while since I worked on the prototype, but I think I've still got a decent idea of what it does. 🙂)
